rdg_soccer_hellopage:
    pattern:  /hello/{name}
    defaults: { _controller: RdgSoccerBundle:Default:index }

rdg_soccer_homepage:
    pattern:  /
    defaults: { _controller: RdgSoccerBundle:Default:home }
       